name: Run Web Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Kör var 5:e minut

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repo
      uses: actions/checkout@v4

    - name: Ställ in Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installera beroenden
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Återställ produkt-cache
      uses: actions/cache@v4
      with:
        path: |
          seen_products.json
          available_products.json
        key: product-cache
        restore-keys: |
          product-cache

    - name: Kör monitor-script
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python main.py

    - name: Spara produkt-cache igen
      uses: actions/cache@v4
      with:
        path: |
          seen_products.json
          available_products.json
        key: product-cache
